version: 1.0.{build}
environment:
  access_token:
    secure: uKzWL2r0ujyYqzEyuSJcyhyIMD2maX8Bz9h8qUQAgFVsP2TI6TX/vKM8HDOQkS/q
install:
- ps: Install-Product node 0.12
- npm install
- git checkout --orphan resources -f
build_script:
- node --version
- npm --version
- node load-feeds.js
on_success:
- git config --global credential.helper store
- git config user.email "david.driscoll@gmail.com"
- git config user.name "David Driscoll"
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git reset
- git add resources/
- git add frameworks/
- git commit -m "Updating resources from build..."
- git push origin resources -f
